-- if IsServer() then
--     if CDOTA_Ability_Lua.GetCastRangeBonus_Engine == nil then
--         CDOTA_Ability_Lua.GetCastRangeBonus_Engine = CDOTA_Ability_Lua.GetCastRangeBonus
--     end
--     function CDOTA_Ability_Lua:GetCastRangeBonus(h)
--         return CDOTA_Ability_Lua.GetCastRangeBonus_Engine(self, h)
--     end
-- else
--     if C_DOTA_Ability_Lua.GetCastRangeBonus_Engine == nil then
--         C_DOTA_Ability_Lua.GetCastRangeBonus_Engine = C_DOTA_Ability_Lua.GetCastRangeBonus
--     end
--     function C_DOTA_Ability_Lua:GetCastRangeBonus(h)
--         return C_DOTA_Ability_Lua.GetCastRangeBonus_Engine(self, h)
--     end
-- end